### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'dropdownListProps.ListHeaderComponent')

### ISSUE THREAD

**Issue by samih-sghier** [siemiatj/react-native-modal-dropdown#72]
Getting the following error:
 **TypeError: undefined is not an object (evaluating 'dropdownListProps.ListHeaderComponent')**

The component was working fine until recently. After debugging the issue is coming from the "options" prop. This is what my code looks like: 
`<ModalDropdown options={housingType} defaultValue={optionLeft || 'Type'} onSelect={(itemValue) => this.handleChangeHousingType(itemValue, dispatch)} />`

**Comment by silldepair** [comment]
same problem, so is there any fix ?

**Comment by ahmed563** [comment]
Any update on this?

**Comment by ahmed563** [comment]
@samih-sghier This should fix it:
<ModalDropdown **dropdownListProps={{}}** options={housingType} defaultValue={optionLeft || 'Type'} onSelect={(itemValue) => this.handleChangeHousingType(itemValue, dispatch)} />

i.e. by adding **dropdownListProps={{}}**

**Comment by prathik-s** [comment]
@ahmed563 The problem still persists even after adding dropdownListProps={{}}.
